
services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: graphroutes-api
    environment:
      # Solo credenciales Neo4j (la API descubre la IP)
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASS=${NEO4J_PASSWORD:-neo4j}
      - SERVER_PORT=${SERVER_PORT:-8080}

      # (Opcional) si quieres que lea valores Spring desde env:
      # - SPRING_PROFILES_ACTIVE=prod

    ports:
      - "8080:8080"

    # Si tu AWS CLI está configurada en ~/.aws, monta el perfil para que el SDK
    # vea las credenciales sin que tú hagas nada.
    volumes:
      - ~/.aws:/root/.aws:ro

    networks:
      - graphnet
    restart: unless-stopped

networks:
  graphnet:
    external: true
    name: graphnet
